export default {
  definitions:{
    "moreinfo":"Cliquez sur le noeud pour plus d'informations",
    "NodeID":"NodeID",
    "Longitude":"Longitude",
    "Latitude":"Latitude",
    
    "Bed Elev.":"Élévation du lit, m",
    "Speed":"Vitesse moyenne du courant de marée, m/s",
    "AEP":"Production annuelle d'énergie, MWh/année",
    
    "Élévation":"Élévation du lit, m",
    "Vitesse":"Vitesse moyenne du courant de marée, m/s",
    "PAE":"Production annuelle d'énergie, MWh/année",
    
    "m":"m",
    "m/s":"m/s",
    "MWh/y":"Megawatt-hour per year",
    "MWh/year":"Megawatt-hour per year",
    "MWh/a":"Megawatt-hour par année",
    "MWh/année":"Megawatt-hour par année",
  },
  topheader:{
    lng:'English',
    home:"Accueil",
    title:"Atlas des ressources énergétiques marines du Canada (Arctique)",
    stitle:"AREMCAN (Arctique)",
    about:"À propos",
    disclaimer:"Clause de non-responsabilité",
    contact:"Contactez",
  },
  legend:{
    references:"Référence(s)",
    title:"Légende",
    bathymetry:"Données bathymétriques",
    model:"Données du modèle",
    report:"Rapport technique",
    chs:"SHC",
    datareference:"Les données ont été calculées à l'aide d'un modèle numérique. Plus d'infos ... (à venir)",
    chsreference:"Plus d'infos ... (à venir)",
  },
  plot:{
    wl:"Hauteur de marée",
    wlt:"Hauteur de marée (Cycle petide/grande marée typique)",
    speed:"Courant de marée",
    speed2:"Courant de marée (stats)",
    wlu:"Hauteur, m",
    speedt:"Courant de marée, m/s (Cycle petide/grande marée typique)",
    speedu:"Vitesse, m/s",
    speeddu:"Direction des courants de marée, m/s",
    speedp:"Probabilité des courants de marée",
    speedpy:"Probabilité de dépassement, %",
    speedpx:"Vitesse, m/s",
  },
  tooltip:{
    hidemodel:"Cacher les Données du modèle numérique",
    showmodel:"Afficher les Données du modèle numérique",
    hidechs:"Cacher les données bathymétriques (SHC)",
    showchs:"Afficher les données bathymétriques (SHC)",
  },  
};
